name: go_coverage
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.2
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Test
        run: go test -race -v -cover -coverprofile=coverage.out ./...
        working-directory: ./src/github.com/${{ github.repository }}/app
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./src/github.com/${{ github.repository }}/app/coverage.out
